#!/usr/bin/env sh
cd next/sponsauru

echo '🏗️👷 Styling your project before committing 👷‍♂️🏗️'
echo 'please be patient, this may take a while...'

yarn run lint ||
(
    echo '🔨❌ Yoo, you have a problem in your code. Check linter 🔨❌
          Run 'npm run lint', add changes and try commit again.';
    false;
)

echo '🎉 No error found: committing this now.... ✨🚀🏄‍♂️🍻'

npx lint-staged
