export const mockedQuests = [
  {
    name: 'follow-buddylinkapp',
    displayName: 'Follow BuddyLinkApp',
    image: '/logo.webp',
    owner: 'us-east-1:8238c320-2f78-ca67-bc74-017d3d2e85fc',
    status: 'active',
    config: {
      PointValue: 1000,
      RepeatFrequency: 'daily',
      UseLastSuccessAsEpoch: false,
      Timezone: 0,
      MaximumTimeToComplete: 0,
      RepeatLimit: 0,
    },
    trigger: {
      type: 'social',
      provider: 'twitter',
      args: {
        content: 'test content',
        operator: 'include_content',
        profile: 'https://x.com/BuddyLinkApp',
      },
    },
  },
  {
    name: 'follow-laddercaster',
    displayName: 'Follow LadderCaster',
    image: '/logo.webp',
    owner: 'us-east-1:8238c320-2f78-ca67-bc74-017d3d2e85fc',
    status: 'active',
    config: {
      PointValue: 1000,
      RepeatFrequency: 'daily',
      UseLastSuccessAsEpoch: false,
      Timezone: 0,
      MaximumTimeToComplete: 0,
      RepeatLimit: 0,
    },
    trigger: {
      type: 'social',
      provider: 'twitter',
      args: {
        content: 'test content',
        operator: 'include_content',
        profile: 'https://x.com/LadderCaster',
      },
    },
  },
  {
    name: 'follow-aeyakovenko',
    displayName: 'Follow Anatoly Yakovenko',
    image: '/logo.webp',
    owner: 'us-east-1:8238c320-2f78-ca67-bc74-017d3d2e85fc',
    status: 'active',
    config: {
      PointValue: 500,
      RepeatFrequency: 'daily',
      UseLastSuccessAsEpoch: false,
      Timezone: 0,
      MaximumTimeToComplete: 0,
      RepeatLimit: 0,
    },
    trigger: {
      type: 'social',
      provider: 'twitter',
      args: {
        content: 'test content',
        operator: 'include_content',
        profile: 'https://x.com/aeyakovenko',
      },
    },
  },
  {
    name: 'follow-themoonboots',
    displayName: 'Follow The Moon Boots',
    image: '/logo.webp',
    owner: 'us-east-1:8238c320-2f78-ca67-bc74-017d3d2e85fc',
    status: 'active',
    config: {
      PointValue: 200,
      RepeatFrequency: 'daily',
      UseLastSuccessAsEpoch: false,
      Timezone: 0,
      MaximumTimeToComplete: 0,
      RepeatLimit: 0,
    },
    trigger: {
      type: 'social',
      provider: 'twitter',
      args: {
        content: 'test content',
        operator: 'include_content',
        profile: 'https://x.com/themoonboots',
      },
    },
  },
  {
    name: 'follow-calvinmaighan',
    displayName: 'Follow Calvin Maighan',
    image: '/logo.webp',
    owner: 'us-east-1:8238c320-2f78-ca67-bc74-017d3d2e85fc',
    status: 'active',
    config: {
      PointValue: 200,
      RepeatFrequency: 'daily',
      UseLastSuccessAsEpoch: false,
      Timezone: 0,
      MaximumTimeToComplete: 0,
      RepeatLimit: 0,
    },
    trigger: {
      type: 'social',
      provider: 'twitter',
      args: {
        content: 'test content',
        operator: 'include_content',
        profile: 'https://x.com/calvinmaighan',
      },
    },
  },
  {
    name: 'like-solana-devs',
    displayName: 'Like Solana Devs Post',
    image: '/logo.webp',
    owner: 'us-east-1:8238c320-2f78-ca67-bc74-017d3d2e85fc',
    status: 'active',
    config: {
      PointValue: 100,
      RepeatFrequency: 'daily',
      UseLastSuccessAsEpoch: false,
      Timezone: 0,
      MaximumTimeToComplete: 0,
      RepeatLimit: 0,
    },
    trigger: {
      type: 'social',
      provider: 'twitter',
      args: {
        content: 'test content',
        operator: 'include_content',
        profile: 'https://x.com/solana_devs/status/1794024427455209727',
      },
    },
  },
  {
    name: 'retweet-solana-devs',
    displayName: 'RT Solana Devs Post',
    image: '/logo.webp',
    owner: 'us-east-1:8238c320-2f78-ca67-bc74-017d3d2e85fc',
    status: 'active',
    config: {
      PointValue: 100,
      RepeatFrequency: 'daily',
      UseLastSuccessAsEpoch: false,
      Timezone: 0,
      MaximumTimeToComplete: 0,
      RepeatLimit: 0,
    },
    trigger: {
      type: 'social',
      provider: 'twitter',
      args: {
        content: 'test content',
        operator: 'include_content',
        profile: 'https://x.com/solana_devs/status/1794024427455209727',
      },
    },
  },
  {
    name: 'like-buddylinkapp-post',
    displayName: 'Like BuddyLinkApp Post',
    image: '/logo.webp',
    owner: 'us-east-1:8238c320-2f78-ca67-bc74-017d3d2e85fc',
    status: 'active',
    config: {
      PointValue: 100,
      RepeatFrequency: 'daily',
      UseLastSuccessAsEpoch: false,
      Timezone: 0,
      MaximumTimeToComplete: 0,
      RepeatLimit: 0,
    },
    trigger: {
      type: 'social',
      provider: 'twitter',
      args: {
        content: 'test content',
        operator: 'include_content',
        profile: 'https://x.com/BuddyLinkApp/status/1790802041608315373',
      },
    },
  },
  {
    name: 'retweet-buddylinkapp-post',
    displayName: 'RT BuddyLinkApp Post',
    image: '/logo.webp',
    owner: 'us-east-1:8238c320-2f78-ca67-bc74-017d3d2e85fc',
    status: 'active',
    config: {
      PointValue: 100,
      RepeatFrequency: 'daily',
      UseLastSuccessAsEpoch: false,
      Timezone: 0,
      MaximumTimeToComplete: 0,
      RepeatLimit: 0,
    },
    trigger: {
      type: 'social',
      provider: 'twitter',
      args: {
        content: 'test content',
        operator: 'include_content',
        profile: 'https://x.com/BuddyLinkApp/status/1790802041608315373',
      },
    },
  },
];
