import React from 'react';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import Header from '@/components/header';
import { WalletConnectionProvider } from '@/providers/wallet-provider';
import { cn } from '@/lib/utils';
import ReactQueryProvider from '@/providers/react-query-provider';
import SessionProvider from '@/providers/session-provider';
import { Toaster } from '@/components/ui/sonner';
import SignMessageProvider from '@/providers/sign-message-provider';

const popins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(popins.className, 'bg-[#FCF4EE] relative mt-24')}>
        <WalletConnectionProvider>
          <SessionProvider>
            <ReactQueryProvider>
              <Header />
              {children}
            </ReactQueryProvider>
            <SignMessageProvider />
          </SessionProvider>
        </WalletConnectionProvider>
        <Toaster />
      </body>
    </html>
  );
}
