import React from 'react';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import Header from '@/components/header';
import { WalletConnectionProvider } from 'Providers/wallet-provider';
import { cn } from '@/lib/utils';

const popins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(popins.className, 'bg-[#FCF4EE] pt-24')}>
        <WalletConnectionProvider>
          <Header />
          {children}
        </WalletConnectionProvider>
      </body>
    </html>
  );
}
